### ISSUE TITLE
Update all template usage doesn't work for more than 25 steps

### ISSUE THREAD

**Issue by davidroberts63** [bluefin-octopusdeploy/chrome-extension#29]
Originally reported on Octopus Deploy support site:

https://t.co/N7BWeQHbc9

**Comment by davidroberts63** [comment]
Looked into this last night. Pagination got me here. I'm just pulling the first page of template usage results. I'll update the part that get's the steps that use the template all together. Should be able to have that done tonight (1/21/2016 US).

**Comment by davidroberts63** [comment]
Well, maybe not. I'm checking my current installation and it gets all of the usage in one go. I had thought all the APIs were paginated. Need to dig further

**Comment by matt-richardson** [comment]
Just tested it with 28 projects - worked fine.
Then tried with 51 projects - worked fine.

Tested with BlueFin 1.3.5
Octopus 3.2.17

**Comment by davidroberts63** [comment]
This was fixed with commit d50ffbbdb9a2c9dd764844fbdb56abdcf2bb1068.
