### ISSUE TITLE
New feature: ability to view the deployment process of a release

### ISSUE THREAD

**Issue by matt-richardson** [bluefin-octopusdeploy/chrome-extension#36]
At the moment, you can only view the latest deployment process, not that of an older release (even though the information is available).

I've done an [initial spike](https://github.com/ASOS/OctoPygmy/tree/view-release-deployment-process) of it - would appreciate your thoughts!

**Comment by davidroberts63** [comment]
This is an awesome idea. Don't need it often but it has been awkward in the past to be able to see just the variables for an old release but no the actual process.

**Comment by matt-richardson** [comment]
Cool. Should have a PR ready tomorrow.

**Comment by matt-richardson** [comment]
Implemented by #38.
