### ISSUE TITLE
Bluefin not recognizing Octopus installation

### ISSUE THREAD

**Issue by andrewogburn** [bluefin-octopusdeploy/chrome-extension#61]
I have the blue fin extension installed in Chrome, but it is not working with my company's Octopus Installation. Is there something required in the URL or something for it to be recognized? We are currently just accessing the instance with the server name. Below is a screenshot.

Thank you.

![image](https://cloud.githubusercontent.com/assets/10116205/16116930/79f1a4aa-339d-11e6-9f58-0e94630ff06a.png)

**Comment by davidroberts63** [comment]
Ahh, currently Bluefin only works for Octopus Deploy installations that are at the root of a domain. Specifically the Chrome extension is setup to look for https:/*/app# but not anything in additional folders.

It's been asked for only a couple times before. And I've been meaning to look into how to allow that. But there is no workaround at the moment.

**Comment by dvdgutzmann** [comment]
I'm  experiencing the same problem. Our Octopus installation resides at http://{hostname}/octopus/app# (no https) and Bluefin is somehome not picking it up.  Is that expected?

Thank you!

**Comment by davidroberts63** [comment]
This has just been fixed with #65. I just published the update to the Chrome webstore as version 1.52.15. Should be available in about an hour from now. Thanks to @kapopken for that pull request.
