### ISSUE TITLE
Improve Configure Dashboard usability

### ISSUE THREAD

**Issue by koolraap** [bluefin-octopusdeploy/chrome-extension#67]
Not sure if Blue Fin can fix the width of the Configure your dashboard page? It's close to unusable where I work because our project names are quite lengthy, often the bit I need to know is not visible:

![image](https://cloud.githubusercontent.com/assets/9983153/17426528/23335dba-5b1c-11e6-90df-9df73a97f66c.png)

With some judicious HTML hacking (remove -narrow)
    `<div class="form-group form-group-narrow ng-isolate-scope" label="Projects">`
to
 `<div class="form-group form-group ng-isolate-scope" label="Projects">`

results in

![image](https://cloud.githubusercontent.com/assets/9983153/17426584/bb87e8ce-5b1c-11e6-944d-06a26b370997.png)

**Comment by davidroberts63** [comment]
We can look into this. Good work on finding out the HTML to modify.

**Comment by matt-richardson** [comment]
This is fixed in Octopus 3.3.21... Not sure if its worth fixing here, though it would be pretty simple...

**Comment by davidroberts63** [comment]
Ahhh, excellent.  @koolraap are you using at least 3.3.21? If not we may add this into Bluefin for prior versions of Octopus.

**Comment by koolraap** [comment]
We're on 3.2.24 at the moment. We're going to upgrade to 3.4.x in a couple of months. It's not super-urgent, I can F12-hack the HTML when I need to.
