### ISSUE TITLE
Edit step as JSON broken with Octopus 3.4.9

### ISSUE THREAD

**Issue by DavidDeSloovere** [bluefin-octopusdeploy/chrome-extension#70]
Turns out "Edit step as JSON" is actually part of the bluefin extension :-)

This doesn't work anymore for me on the (currently) latest version of OD, which is 3.4.9
http://help.octopusdeploy.com/discussions/problems/47594-edit-step-as-json-broken

Hope you can find a way to make this compatible with the newer versions.

**Comment by matt-richardson** [comment]
Hmmm. Looks like it got broken in 3.4, with an upgrade of angular-ui-bootstrap.

Looks like it broke:
* edit step as json
* view release deployment process
* view resultant variables list

Its gonna be a challenge... Will have to ponder how we can do it.

**Comment by matt-richardson** [comment]
Hi @DavidDeSloovere, this has been fixed and pushed to the chrome store now. Your extension should automatically update, but you can also go to the extensions page and hit 'update now'.

Let us know how it goes!

**Comment by aspiringtfsguru** [comment]
Running bluefin 1.52.15 and Octopus 3.4.10 and the clone step menu option is not there.

**Comment by davidroberts63** [comment]
Hmmmmm. Looking. I may have messed up the virtual directory support.

**Comment by davidroberts63** [comment]
Yep, that was me. Apparently I only 'thought' I had committed and push the removal of the '/' in the manifest. Fixing now. Will publish within an hour or two.

**Comment by davidroberts63** [comment]
Fixed. Published. Should be available within an hour.

**Comment by aspiringtfsguru** [comment]
Works now. Thanks for the quick turnaround.
