### ISSUE TITLE
'Update All' for referencing projects after template step update has disappeared 

### ISSUE THREAD

**Issue by BinLiuSeattle** [bluefin-octopusdeploy/chrome-extension#85]
In the most recent version, 1.52.18, 'Update All' link, under Library > Step Templates > {templateName} > Usage, has disappeared. The page still displays a list of all projects using the template step, along with Step, Version, and column indicating 'Out of date'.

**Comment by matt-richardson** [comment]
What version of Octopus are you using, @BinLiuSeattle?

**Comment by BinLiuSeattle** [comment]
@matt-richardson 3.7.3

**Comment by matt-richardson** [comment]
Sorry about that @BinLiuSeattle - silly mistake on my part. I've just raised a PR to fix it.

**Comment by BinLiuSeattle** [comment]
Thanks @matt-richardson.
