### ISSUE TITLE
View release deployment process no longer works

### ISSUE THREAD

**Issue by nirw** [bluefin-octopusdeploy/chrome-extension#95]

**Comment by matt-richardson** [comment]
Can you provide a little more information about what "no longer works" means?
Does it show anything?
Does it log anything to the console?
What version of Octopus are you using?

**Comment by gurufordy** [comment]
I've just run into the same issue with OD 3.15.8 and latest extension version. The popup appears and it's got nothing in it. Below is a screenie of the Chrome developer console error:

![image](https://user-images.githubusercontent.com/5593892/29179005-19a28364-7deb-11e7-84bd-631bd5419433.png)

**Comment by casterlight** [comment]
Same issue with OD 3.14.1 . The ShowProcesses gui just shows a blank box. This feature has been great for me.

![capture](https://user-images.githubusercontent.com/31048972/29335915-dad1fa58-81d1-11e7-87d9-c6a29a5bcbd9.JPG)

**Comment by casterlight** [comment]
David -
Any update on this one ?
